### ISSUE TITLE
Cannot create order

### ISSUE THREAD

**Issue by pawel-kontakt** [zendesk/basecrm-java#43]
`sdkClient.orders().create(order)` is throwing:
> com.getbase.exceptions.ResourceException: httpStatus=422, logref='b1vds-kvaii-hp1vf-l11q0', httpMethod=POST, url=/v2/orders, errors=BaseError{code='missing', message='attribute is missing', details='This field is required.', resource='order', field='/data/deal_id'}

**Comment by piotr-szczesniak** [comment]
🥇
